# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

TransferModalUnfoldings <- function(S, d1, d2, r1, r2, r3) {
    .Call(`_tensorMQR1_TransferModalUnfoldings`, S, d1, d2, r1, r2, r3)
}

produceZ <- function(X) {
    .Call(`_tensorMQR1_produceZ`, X)
}

Estimation <- function(Y, X, S, U, V, optsList) {
    .Call(`_tensorMQR1_Estimation`, Y, X, S, U, V, optsList)
}

setuplambda <- function(Y, X, S, U, V, isPenU, nlam, setlam) {
    .Call(`_tensorMQR1_setuplambda`, Y, X, S, U, V, isPenU, nlam, setlam)
}

EstPenColumn <- function(Y, X, S, U, V, lambda, optsList, optsList_pen) {
    .Call(`_tensorMQR1_EstPenColumn`, Y, X, S, U, V, lambda, optsList, optsList_pen)
}

EstPenSingle <- function(Y, X, S, U, V, lambda, optsList, optsList_pen) {
    .Call(`_tensorMQR1_EstPenSingle`, Y, X, S, U, V, lambda, optsList, optsList_pen)
}

EstimationD3 <- function(Y, X) {
    .Call(`_tensorMQR1_EstimationD3`, Y, X)
}

