# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

TransferModalUnfoldings <- function(S, d1, d2, r1, r2, r3) {
    .Call(`_tensorMQR1_TransferModalUnfoldings`, S, d1, d2, r1, r2, r3)
}

setuplambdaUn <- function(Y, Z, A, B, C, S, nlam, setlam) {
    .Call(`_tensorMQR1_setuplambdaUn`, Y, Z, A, B, C, S, nlam, setlam)
}

produceZ <- function(X) {
    .Call(`_tensorMQR1_produceZ`, X)
}

produceX2 <- function(X) {
    .Call(`_tensorMQR1_produceX2`, X)
}

TransferTtoP <- function(D3, p, q) {
    .Call(`_tensorMQR1_TransferTtoP`, D3, p, q)
}

TransferPtoT <- function(coef, p, q) {
    .Call(`_tensorMQR1_TransferPtoT`, coef, p, q)
}

setuplambda <- function(Y, X, S, U, V, isPenU, nlam, setlam) {
    .Call(`_tensorMQR1_setuplambda`, Y, X, S, U, V, isPenU, nlam, setlam)
}

EstFR <- function(Y, X) {
    .Call(`_tensorMQR1_EstFR`, Y, X)
}

EstUnconstr <- function(Y, X, S, A, B, C, mu, optsList) {
    .Call(`_tensorMQR1_EstUnconstr`, Y, X, S, A, B, C, mu, optsList)
}

Estimation <- function(Y, X, S, U, V, mu, optsList) {
    .Call(`_tensorMQR1_Estimation`, Y, X, S, U, V, mu, optsList)
}

EstPenColumn <- function(Y, X, S, U, V, lambda, optsList, optsList_pen) {
    .Call(`_tensorMQR1_EstPenColumn`, Y, X, S, U, V, lambda, optsList, optsList_pen)
}

EstPenSingle <- function(Y, X, S, U, V, lambda, optsList, optsList_pen) {
    .Call(`_tensorMQR1_EstPenSingle`, Y, X, S, U, V, lambda, optsList, optsList_pen)
}

